; --- Configurações Gerais ---
[env]
platform = freescalekinetis
board = frdm_kl25z
framework = zephyr
platform_packages =
    platformio/framework-zephyr@~3.40200.0

monitor_speed = 115200

; --- Ambiente do Transmissor (TX) ---
[env:frdm_kl25z_tx]
build_flags =
    -DROLE_TX

; --- Ambiente do Receptor (RX) ---
[env:frdm_kl25z_rx]
build_flags =
    -DROLE_RX