[env:frdm_kl25z_tx]
platform = freescalekinetis
framework = zephyr
board = frdm_kl25z

platform_packages =
		 platformio/framework-zephyr@~3.40200.0

build_flags =
    -DROLE_TX

[env:frdm_kl25z_rx]
platform = freescalekinetis
board = frdm_kl25z
framework = zephyr

platform_packages =
		 platformio/framework-zephyr@~3.40200.0

build_flags =
    -DROLE_RX